on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: |
          set -x
          find ./ -type f
          ls -l /home/runner/work/github-actions/github-actions
          ls -l /home/runner/work/github-actions/github-actions/hello-world-javascript-action
          cat /home/runner/work/github-actions/github-actions/hello-world-javascript-action/action.yml
      - name: Hello world action step
        id: hello
        uses: ./hello-world-javascript-action
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
